version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: sall@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - my-network
  nestapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestapp
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-network

volumes:
  postgres_data:


networks:
  my-network:
